### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by mafineeek** [spacebarchat/spacebarchat#10]
Have a look at http://docs.fosscord.com/ to get an overview about the project.
Read the documentation and setup the development environment.
You should be familiar with the [discord api](https://discord.dev/) or read more about it in the [docs](https://discord.dev/).

Then create feature request issue in one our repos or comment on an existing one.
Or just write us on our [development server](https://discord.gg/ZrnGQP6p3d).

[Repos list](https://github.com/fosscord/fosscord)

After making an issue, wait for message from one of our staff.
You will get informations about your feature.
Then, you can Pull Request that, and wait for review.

**Comment by Flam3rboy** [comment]
If you don't know where to create an issue just create one here and we'll transfer it to the corresponding repository

**Comment by Flam3rboy** [comment]
Or if you want to setup all repositories have a look at the [Readme](https://github.com/fosscord/fosscord/tree/main/setup)

**Comment by Flam3rboy** [comment]
guide will be continued here: https://docs.fosscord.com/contributing/
