### ISSUE TITLE
Presence not working

### ISSUE THREAD

**Issue by Adithr123** [spacebarchat/spacebarchat#127]
*As title says*

**Comment by Luna-devv** [comment]
If you mean the status display of the other members;
It works, it just doesn't update while you are using Fosscord. Aka if you reload your browser it should update. At least this is my experience.

**Comment by Adithr123** [comment]
![image](https://user-images.githubusercontent.com/85714072/152890985-fe4d6070-11d5-489c-b05a-3ca5525a8668.png)
This is after reloading 5 times...

**Comment by erkinalp** [comment]
Presence works fine. The actual issue is lazy guild sync is broken.
