### ISSUE TITLE
Fosscord is being stereotyped by Google and other companies as against their ToS, they are censoring information about it.

### ISSUE THREAD

**Issue by ghost** [spacebarchat/spacebarchat#173]
**This may be an offtopic of code-writing developement, this is a serious issue where posts about Fosscord on other websites are getting censored by companies, or your website can be blocked by ISPs for telling about Fosscord, when Fosscord is just an innocent concept**
Alright, it was kind of a weird decision by me, but i just wanted to tell people about this project on Youtube by making a tutorial on how to host it. I just said there to run it with NPM and other basic instructions. My video got a strike after a month: 
<img width="903" alt="removed" src="https://user-images.githubusercontent.com/110140779/184512111-a67bd4a8-7c07-4185-acc1-d443122d03e4.png">

This type of content strike on Youtube says that my video has one of these violations:
" _Hacking: Demonstrating how to use computers or information technology with the intent to steal credentials, compromise personal data or cause serious harm to others such as (but not limited to) hacking into social media accounts.
Bypassing payment for digital content or services: Showing viewers how to use apps, websites, or other information technology to gain unauthorized access to audio content, audiovisual content, full video games, software, or streaming services that normally require payment._ "

I think that the launch script having an ANSI text displaying "FOSSCORD" in the terminal makes it look like most of discord hacks, when it's not even counts as pirating nor accessing paid content for free. I understand myself what Fosscord is, been hosting my own instance, viewed the source code and controlled the SQLite database, 'cause i'm into servers and scripting. But normal people don't, they may idiotically count it as a Discord cracked client with free nitro when they firstly hear about it. This theory about how people are stereotyping anything that has a similar interface as cracked or illegal version of original is really weird to be real, but i'm afraid that this is actually a fact and Fosscord reputation can be under attack... 
<img width="1086" alt="probably against tos" src="https://user-images.githubusercontent.com/110140779/184515450-201e82b1-0b3c-470f-924a-a963d696e09f.png">

I suggest changing the name and user interface from having anything related to Dis**cord**, so people won't complain. But that may kill the entire idea behind this project of making a decentralized Discord-like alternative.

**Comment by TheGoldenSun** [comment]
Please report this directly to YouTube before notifying Google as well, thank you.

**Comment by Hoot679** [comment]
the strike is actually really dumb, as i've seen videos saying how to get full games for free yet they don't get banned
