### ISSUE TITLE
Broken setup link in README

### ISSUE THREAD

**Issue by developomp** [spacebarchat/spacebarchat#195]
replace `https://docs.fosscord.com/server/setup` with `https://docs.fosscord.com/setup/server/#setup`

**Comment by Puyodead1** [comment]
`https://docs.fosscord.com/setup/server#setup`*

**Comment by developomp** [comment]
> `https://docs.fosscord.com/setup/server#setup`*

either one works but that's the link I get when I click the anchor in the right sidebar.

**Comment by Puyodead1** [comment]
It may work, but it’s not really the correct way.
