### ISSUE TITLE
I miss "Fosscord"

### ISSUE THREAD

**Issue by Eevee-Gaming** [spacebarchat/spacebarchat#211]
I wish there was an archived version of fosscord, that app used to help me alot. Is there any archive or anything ? "Spacebar" dosen't look promising.

**Comment by Puyodead1** [comment]
"Fosscord" and "Spacebar" are the same thing. We had to remove the test client as it was discords intellectual property and they sent us a C&D. Not sure what you expect to get from opening an issue.
