### ISSUE TITLE
Apache2 reverse proxy

### ISSUE THREAD

**Issue by MyUncleSam** [spacebarchat/spacebarchat#213]
Hi there,

does anyone has a working Apache2 reverse proxy configuration for spacebar? At the moment I tried a lot of different stuff but nothing worked. On registration tab the client always wants to connect to http://localhost:3001 instead of the domain given in the first view.

**Comment by MaddyUnderStars** [comment]
You need to set the API, gateway, and CDN public endpoints in the spacebar server configuration. Gateway is a websocket, the rest is http as expected
