### ISSUE TITLE
Mobile display issues

### ISSUE THREAD

**Issue by stemy2** [spacebarchat/spacebarchat#214]
Hello,

There are some issue with the display in the mobile version of the app.

-Servers can be seen only in landscape mode.
-Channels list is unavailable.

**Comment by MaddyUnderStars** [comment]
Hi. We're currently focusing on desktop usage at the moment. Feel free to contribute better mobile support if you'd like. Also, make sure to create issues in the correct repositories next time: https://github.com/spacebarchat/client
