### ISSUE TITLE
アカウント

### ISSUE THREAD

**Issue by kkk2z** [spacebarchat/spacebarchat#215]
If you have an issue regarding the [server](https://github.com/spacebarchat/server), [client](https://github.com/spacebarchat/server), [docs](https://github.com/spacebarchat/server), or our other repos, please create an issue in those repos instead of here!
アカウントが作れない！

**Comment by MaddyUnderStars** [comment]
Due to spam, registration on our official instance is currently disabled. Sorry about that. We might look into creating a locked down demo account for people to use soon.

**Comment by jiyu8iighx** [comment]
If you cannot open a demo, is there some preview images?

**Comment by JF6DEU** [comment]
I think this is to spam, but It might he hasn't know how to use GitHub.
I can't say it because I'm as same, but he might not know where to use Issues.
