### ISSUE TITLE
Add native support for bridging to Matrix

### ISSUE THREAD

**Issue by ajhalili2006** [spacebarchat/spacebarchat#54]
## About this issue

Support for bridging to Matrix should be an first-class feature, either through an built-in feature or adding backwards-compatible Matrix AS API.

## Any possible roadblocks

Since the Matrix spec is not yet an official spec at IETF, like ActivityPub, and as per the docs, writing Matrix homeservers are magnitudes harder than writing bridges, bots, or clients.

**Comment by erkinalp** [comment]
The esiest way to bridge Discord to Matrix in the server-server level is actually implementing one of the servers as a plugin of the other.

**Comment by ShadowJonathan** [comment]
related: https://github.com/fosscord/fosscord-api/issues/105

**Comment by erkinalp** [comment]
@FSG-Cat

**Comment by FSG-Cat** [comment]
Well one option is to add some kind of AS API to Fosscord so you can have a Matrix AS that talks AS API Matrix and Talks AS API Fosscord.

Alternatively you could strap a fosscord server into a matrix homeserver but i actually think a dual pronged aproatch is a way better idea. 

An AS API would be way more generic than making specialised implementations after all.

**Comment by erkinalp** [comment]
@FSG-Cat You would love #171 then. Each puppet user as a full-blown user, controlled by an account controller, just like Matrix AS API.
