### ISSUE TITLE
fosscord.com terms of service

### ISSUE THREAD

**Issue by erkinalp** [spacebarchat/spacebarchat#90]
The demo instance needs its own terms of service.

**Comment by xNaCly** [comment]
No

**Comment by Flam3rboy** [comment]
We'll do it when we'll release the first stable version

**Comment by valkyrienyanko** [comment]
What kind of ToS are we talking about? Does this ToS still apply if it is self-hosted on your own personal machine?

**Comment by popeda97** [comment]
> The demo instance needs its own terms of service.
