### ISSUE TITLE
Matrix Bridge

### ISSUE THREAD

**Issue by Danoloan10** [spacebarchat/spacebarchat#97]
It would be nice if fosscord supported the [Matrix API](https://matrix.org), so that it could connect people from it's environment too.

I recon that implementing the Matrix API in the server could be too much; in that case, making it easy to make a bridge between fosscord and matrix could be a more feasible idea.

In any case, considering this option from the beginning should ease future attempts to interconnect both.

**Comment by othello777** [comment]
This seems like a really good idea. I tried matrix, but it doesn't have that good of servers, bots, or online indicators. It would be really cool not to have to have a lot of clients open. If this could do discord, matrix, and its own fosscord all in one, that would be very cool.

**Comment by developomp** [comment]
@MaddyUnderStars can you close this issue as "not planned" instead?

![image](https://user-images.githubusercontent.com/40858122/235653733-e670fed8-fe4b-405f-8def-06959de9b5eb.png)

**Comment by MaddyUnderStars** [comment]
I closed them in bulk, github doesn't give you the option

**Comment by erkinalp** [comment]
https://github.com/matrix-org/matrix-appservice-discord/issues/782
